services:
  bot:
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./eval:/app/eval

  beta-web:
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./eval:/app/eval
